version: "2"

services:
  springbootdb:
    container_name: springbootdb
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=springbootdb
    ports:
      - "5432:5432"

  lifehostdb:
    container_name: lifehostdb
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lifehostdb
    ports:
      - "5431:5432"
